version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Madrid'  # Ajusta según tu zona horaria
      WEBPASSWORD: 'tu_contraseña_segura'  # Establece una contraseña segura para la interfaz web
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    restart: unless-stopped
volumes:
  pihole_data:
  dnsmasq_data:
